- type: job
  id: TribalHealer
  setPreference: true
  name: job-name-tribal-healer
  description: job-description-tribal-healer
  playTimeTracker: TribalHealer
  startingGear: TribalHealerGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-tribal

- type: startingGear
  id: TribalHealerGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTribal
    back: ClothingBackpackHydroponicsFilled #placeholder
    outerClothing: N14ClothingOuterTribalArmor
    belt: ClothingBeltPlantFilled
  innerClothingSkirt: N14ClothingUniformJumpskirtTribal
  satchel: ClothingBackpackSatchelHydroponicsFilled #placeholder
  duffelbag: ClothingBackpackDuffelFilled #placeholder

- type: playTimeTracker
  id: TribalHealer